name: Monitor Upstream Changes

on:
  schedule:
    - cron: "0 2 * * *"  # Adjust for your desired schedule
  workflow_dispatch:  # Allows manual trigger

jobs:
  check_for_upstream_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git user for GitHub Actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          if [ "${{ github.repository }}" == "khalandarsihan/frappe" ]; then
            git remote add upstream https://github.com/frappe/frappe.git
          elif [ "${{ github.repository }}" == "khalandarsihan/erpnext" ]; then
            git remote add upstream https://github.com/frappe/erpnext.git
          elif [ "${{ github.repository }}" == "khalandarsihan/payments" ]; then
            git remote add upstream https://github.com/frappe/payments.git
          fi

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Check for differences
        run: |
          git diff origin/version-15..upstream/version-15 > changes.diff
          if [ -s changes.diff ]; then
            echo "New updates are available in the upstream repository!" > update_notification.txt
          else
            echo "No new updates detected." > update_notification.txt
          fi

      - name: Show results
        run: cat update_notification.txt
